### ISSUE TITLE
存在的问题

### ISSUE THREAD

**Issue by xingstarx** [houxg/Leamonax#1]
1. 干嘛在4.4上都不能安装呢？希望可以支持额
2. 用我自己的账号登陆，首页拉取笔记直接crash了。。

你可以试试下。

感觉删减了那么多代码后，看着比较爽。。

**Comment by FlyingRadish** [comment]
不支持5.0及以下的原因是UI是尽量按照Material design走的，如果支持5.0以下的话还需要做Holo风的适配，还有执行JS脚本的API低版本支持的原因，你可以提pull request我们一起做啊

**Comment by FlyingRadish** [comment]
crash的问题，我在Flurry看到的stack trace是这样的：
```
at model.leamonax.houxg.org.Note.updateTime(Note.java:216)
at network.leamonax.houxg.org.LeaResponseConverter.convert(LeaResponseConverter.java:42)
at network.leamonax.houxg.org.LeaResponseConverter.convert(LeaResponseConverter.java:20)
at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117)
at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:89)
at utils.leamonax.houxg.org.RetrofitUtils.excute(RetrofitUtils.java:37)
at service.leamonax.houxg.org.NoteService.fetchFromServer(NoteService.java:47)
at background.leamonax.houxg.org.NoteSyncService$2.call(NoteSyncService.java:60)
at background.leamonax.houxg.org.NoteSyncService$2.call(NoteSyncService.java:56)
at rx.Observable.unsafeSubscribe(Observable.java:10150)
at operators.internal.rx.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
at schedulers.internal.rx.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
at schedulers.internal.rx.ScheduledAction.run(ScheduledAction.java:55)
at concurrent.util.java.Executors$RunnableAdapter.call(Executors.java:422)
at concurrent.util.java.FutureTask.run(FutureTask.java:237)
at concurrent.util.java.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
at concurrent.util.java.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
at concurrent.util.java.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at concurrent.util.java.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at lang.java.Thread.run(Thread.java:818)
lang.java.IllegalStateException: (Fatal Exception thrown on Scheduler.Worker thread.)
at schedulers.internal.rx.ScheduledAction.run(ScheduledAction.java:59)
at concurrent.util.java.Executors$RunnableAdapter.call(Executors.java:422)
at concurrent.util.java.FutureTask.run(FutureTask.java:237)
at concurrent.util.java.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
at concurrent.util.java.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
at concurrent.util.java.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at concurrent.util.java.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at lang.java.Thread.run(Thread.java:818)
```
似乎和note的时间有关，时间的格式比较多变，可不可以把出问题的note时间贴一下？或者直接修正这个问题提交pull request?

**Comment by xingstarx** [comment]
恩，好的，周末我研究下。。提pr

**Comment by xingstarx** [comment]
你的NotePreviewActivity在我这边显示不出来内容是吧。。功能还没有开发完成吧。。

**Comment by FlyingRadish** [comment]
显示不出来的是图片内容么? 大图下载会花时间, 这里还缺个progressbar没有加上.
其实preview和edit用的是同样的EditorFragment, 我正在考虑把它们合起来会不会更好一点

**Comment by xingstarx** [comment]
不是，就是纯文字的，看样子还是我自己研究吧。我这边没有显示出来内容的。什么都看不到。。
![leanote_2016_11_26_001](https://cloud.githubusercontent.com/assets/8245264/20647276/33ec6e36-b4cb-11e6-84fa-abda4989d104.png)

**Comment by xingstarx** [comment]
你可以说下，你目前做到什么程度了，效果可以多贴几张图的。。

**Comment by FlyingRadish** [comment]
显示空白的问题可以试一下用chrome打开editor然后直接执行相应的js script
完成度这个事情我会在`Tag支持`之后去做
btw，我们似乎在一个issue里边讨论太多事情了，每个问题新开一个issue会比较好，这个issue到此结束吧，非常感谢你的pr:)
